import os
DIR_PATH = os.path.dirname(os.path.abspath(__file__))

from transformers.models.gpt2.modeling_gpt2 import (
    GPT2Attention,
    GPT2MLP,
    GPT2Block,
)

HYPERPARAMS = {
    "seed": 42,
    "learning_rate": 0.00005,
    "mask_learning_rate": 0.2,
    "train_batch_size": 250, 
    "eval_batch_size": 250,
    "train_epoch": 40000,
    "lr_warmup_frac": 0.1,
    "log_step": 100,
    "save_checkpoint_every" : 200,
    "save_state_every": 5000,
    "log_rate_per_epoch": 0.5, 
    "lambda_reg_init": 2.0,
    "lambda_reg_final": 3.0,
}

CONSTANTS = {
    "vowels": ["a", "e", "i", "o", "u"],
    "train_ratio": 0.9,
    "gpt2_linear_types_to_mask": ['c_attn', 'q_attn', 'c_proj', 'c_fc'],
    "gpt2_module_types_to_mask": [GPT2Attention, GPT2MLP, GPT2Block],
}

PATH_DICT = {
    "wordnet_dir": os.path.join(DIR_PATH, "data", "wordnet"),
    "wordnet_targetkg": os.path.join(DIR_PATH, "data", "wordnet", "targetkg"),
    "wordnet_controlkg": os.path.join(DIR_PATH, "data", "wordnet", "controlkg"),
    #
    "conceptnet_lama_dir": os.path.join(DIR_PATH, "data", "conceptnet_lama"),
    "conceptnet_targetkg": os.path.join(DIR_PATH, "data", "conceptnet_lama", "targetkg", "best_format"),
    #
    "csqa_dir": os.path.join(DIR_PATH, "data", "csqa"),
}

CONCEPTNET_REL_VERBALIZATIONS = {
    'AtLocation': [
        "{} is at location {}",
        "{} is at the location {}",
        "{} is typically located at {}",
        "{} is normally located at {}",
        "{} is usually located at {}",
        "{} is typically placed at {}",
        "{} is normally placed at {}",
        "{} is usually placed at {}",
        "{} is typically placed by {}",
        "{} is normally placed by {}",
        "{} is usually placed by {}",
        "{} is located at {}",
        "{} is placed at {}",
        "{} is placed by {}",
        "{} is typically at {}",
        "{} is normally at {}",
        "{} is usually at {}",
        "{} is typically by {}",
        "{} is normally by {}",
        "{} is usually by {}",
        "{} is at {}",
        "{} is by {}",
        "{} is in {}",
        "{} are at location {}",
        "{} are at the location {}",
        "{} are typically located at {}",
        "{} are normally located at {}",
        "{} are usually located at {}",
        "{} are typically placed at {}",
        "{} are normally placed at {}",
        "{} are usually placed at {}",
        "{} are typically placed by {}",
        "{} are normally placed by {}",
        "{} are usually placed by {}",
        "{} are located at {}",
        "{} are placed at {}",
        "{} are placed by {}",
        "{} are typically at {}",
        "{} are normally at {}",
        "{} are usually at {}",
        "{} are typically by {}",
        "{} are normally by {}",
        "{} are usually by {}",
        "{} are at {}",
        "{} are by {}",
        "{} are in {}",
    ],
    'CapableOf': [
        "{} is capable of {}",
        "{} is able to {}",
        "{} are capable of {}",
        "{} are able to {}",
        "{} can {}",
        "{} has the skill of {}",
        "{} has the skill to {}",
        "{} have the skill of {}",
        "{} have the skill to {}"
    ],
    'Causes': [
        "{} causes {}",
        "{} cause {}",
        "{} can cause {}",
        "{} can cause to {}",
        "{} can lead to {}"
    ],
    'CausesDesire': [
        "{} causes a desire of {}",
        "{} causes a desire to {}",
        "{} causes the desire of {}",
        "{} causes the desire to {}",
        "{} cause a desire of {}",
        "{} cause a desire to {}",
        "{} cause the desire of {}",
        "{} cause the desire to {}",
        "{} can cause a desire of {}",
        "{} can cause a desire to {}",
        "{} can cause the desire of {}",
        "{} can cause the desire to {}",
    ],
    'CreatedBy': [
        "{} is created by {}",
        "{} is made by {}",
        "{} is built by {}",
    ],
    'DefinedAs': [
        "{} is defined as {}", 
        "{} can be defined as {}", 
    ],
    'DesireOf': [
        "{} desires of {}",
        "{} wants {}",
        "{} craves {}",
        "{} craves for {}",
        "{} desire of {}",
        "{} want {}",
        "{} crave {}",
        "{} crave for {}",
    ],
    'Desires': [
        "{} desires {}",
        "{} wants {}",
        "{} craves {}",
        "{} craves for {}",
        "{} desire {}",
        "{} want {}",
        "{} crave {}",
        "{} crave for {}",
    ],
    'HasA': [
        "{} has {}",
        "{} have {}",
    ],
    'HasFirstSubevent': [
        "{} has first subevent {}",
        "{} has the prerequisite of {}"
    ],
    'HasLastSubevent': [
        "{} has last subevent {}",
        "{} can lead to {}",
        "{} is a precursor to {}"
    ],
    'HasPrerequisite': [
        "{} has prerequisite {}",
        "{} has the prerequisite to {}",
        "{} has a prerequisite to {}",
        "{} have prerequisite {}",
        "{} have the prerequisite to {}",
        "{} have a prerequisite to {}",
        "{} requires {}",
        "{} require {}",
        "{} requires to {}",
        "{} require to {}",
        "{} needs to {}",
        "{} need to {}",
    ],
    'HasProperty': [
        "{} has property {}",
        "{} has the property {}",
        "{} has the property of being {}",
        "{} has the property of {}",
        "{} has the property to {}",
        "{} is {}",
        "{} have property {}",
        "{} have the property {}",
        "{} have the property of {}",
        "{} can be {}"
    ],
    'HasSubevent': [
        "{} has subevent {}",
        "{} has the subevent {}",
        "{} can have the subevent {}",
        "{} has subevent of {}",
        "{} has the subevent of {}",
        "{} can have the subevent of {}",
    ],
    'InstanceOf': [
        "{} is an instance of {}",
        "{} is {}",
        "{} is a type of {}"
    ],
    'IsA': [
        "{} is {}",
        "{} is a kind of {}",
        "{} is a sort of {}",
        "{} is a hyponym of {}",
        "{} is a type of {}"
    ],
    'LocatedNear': [
        "{} is typically located near {}",
        "{} is normally located near {}",
        "{} is usually located near {}",
        "{} is typically placed near {}",
        "{} is normally placed near {}",
        "{} is usually placed near {}",
        "{} is typically placed by {}",
        "{} is normally placed by {}",
        "{} is usually placed by {}",
        "{} is located near {}",
        "{} is placed near {}",
        "{} is placed by {}",
        "{} is typically near {}",
        "{} is normally near {}",
        "{} is usually near {}",
        "{} is typically by {}",
        "{} is normally by {}",
        "{} is usually by {}",
    ],
    'MadeOf': [
        "{} is made of {}",
        "{} is made up of {}",
        "{} constitutes of {}",
        "{} consists of {}",
        "{} is composed of {}",
        "{} comprises of {}",
        "{} can be made of {}",
        "{} can be made up of {}",
        "{} can constitute of {}",
        "{} can consist of {}",
        "{} can be composed of {}",
        "{} can comprise of {}",

    ],
    'MotivatedByGoal': [
        "{} is motivated by the goal of {}",
        "{} is motivated by the aim of {}",
        "{} is motivated by {}",
        "{} can be motivated by the goal of {}",
        "{} can be motivated by the aim of {}",
        "{} can be motivated by {}",
    ],
    'NotCapableOf': [
        "{} is not capable of {}",
        "{} is not able to {}",
        "{} is unable to {}",
        "{} are not capable of {}",
        "{} are not able to {}",
        "{} are unable to {}",
        "{} cannot {}",
        "{} doesn't have the skill of {}",
        "{} doesn't have the skill to {}",
        "{} don't have the skill of {}",
        "{} don't have the skill to {}"
    ],
    'NotDesires': [
        "{} doesn't desire {}",
        "{} doesn't wants {}",
        "{} doesn't crave {}",
        "{} doesn't crave for {}",
        "{} don't desire {}",
        "{} don't want {}",
        "{} don't crave {}",
        "{} don't crave for {}",
    ],
    'NotHasA': [
        "{} doesn't have {}",
        "{} don't have {}",
    ],
    'NotHasProperty': [
        "{} doesn't have property {}",
        "{} doesn't have the property {}",
        "{} doesn't have the property of being {}",
        "{} doesn't have the property of {}",
        "{} doesn't have the property to {}",
        "{} isn't {}",
        "{} can't be {}"
    ],
    'NotIsA': [
        "{} isn't {}",
        "{} isn't a kind of {}",
        "{} isn't a sort of {}",
        "{} isn't a hyponym of {}",
        "{} isn't a type of {}"
    ],
    'NotMadeOf': [
        "{} isn't made of {}",
        "{} isn't made up of {}",
        "{} doesn't constitute of {}",
        "{} doesn't consist of {}",
        "{} isn't composed of {}",
        "{} doesn't comprise of {}",
        "{} cannot be made of {}",
        "{} cannot be made up of {}",
        "{} cannot constitute of {}",
        "{} cannot consist of {}",
        "{} cannot be composed of {}",
        "{} cannot comprise of {}"
    ],
    'PartOf': [
        "{} is part of {}",
        "{} is an element of {}",
        "{} is a characteristic of {}",
    ],
    'ReceivesAction': [
        "{} receives action {}",
        "{} can be {}",
        "{} is {}",
        "{} are {}",
    ],
    'RelatedTo': [
        "{} is related to {}",
        "{} are related to {}",
        "{} is about {}",
        "{} is in reference to {}",
        "{} is connected with {}",
        "{} relates to {}",
        "{} are related to {}",
        "{} are about to {}",
        "{} are in reference to {}",
        "{} are connected with {}",
        "{} relate to {}",
        ],
    'SymbolOf': [
        "{} is a symbol of {}",
        "{} is a sign of {}",
        "{} symbolizes {}",
        "{} represents {}",
        "{} are symbols of {}",
        "{} are signs of {}",
        "{} symbolize {}",
        "{} represent {}",
    ],
    'UsedFor': [
        "{} is used for {}",
        "{} is intended for {}",
        "{} is designed for {}",
        "{} serves for {}",
        "{} are used for {}",
        "{} are intended for {}",
        "{} are designed for {}",
        "{} serve for {}",
    ]
}