compute_environment: LOCAL_MACHINE
deepspeed_config: {}
#  deepspeed_config_file: /mnt/u14157_ic_nlp_001_files_nfs/nlpdata1/home/bayazit/knowledge-transformers/knowledge_transformers/configs/zero3_offload_config_accelerate.json
#  zero3_init_flag: true
distributed_type: MULTI_GPU
# distributed_type: null
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: null
num_machines: 1
num_processes: 2
use_cpu: false